#:schema node_modules/wrangler/config-schema.json
name = "robbcurrall-com"
compatibility_date = "2024-06-05"
pages_build_output_dir = "./build/client"

# # Does not work with CF Pages yet
# [route]
# custom_domain = true
# pattern = "robbcurrall.com/*"
